"""Added __repr__ for Classes 

Revision ID: 5c8a62c142f7
Revises: 5eb38e9a2647
Create Date: 2019-06-09 14:18:27.742941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8a62c142f7'
down_revision = '5eb38e9a2647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
