"""Added Tables contacts - cities - states

Revision ID: 5eb38e9a2647
Revises: 759a2f885d42
Create Date: 2019-06-09 11:38:05.487916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb38e9a2647'
down_revision = '759a2f885d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
