"""Added Cookie model

Revision ID: a010c9cd1f73
Revises: a26a7d0b22dd
Create Date: 2019-06-09 11:28:08.312739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a010c9cd1f73'
down_revision = 'a26a7d0b22dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('state_name')
    )
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_fname', sa.String(length=255), nullable=False),
    sa.Column('contact_lname', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=15), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_job', sa.String(length=255), nullable=True),
    sa.Column('contact_adr', sa.Text(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('contact_id'),
    sa.UniqueConstraint('contact_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('cities')
    op.drop_table('states')
    # ### end Alembic commands ###
